Default: &defaults
  user: schoolshop
  password: schoolshop
  host: localhost
  port: 5432
  database: schoolshop
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: schoolshop_test
  <<: *defaults

Staging:
  database: schoolshop_staging
  poolsize: 100
  <<: *defaults

Production:
  database: schoolshop_production
  poolsize: 100
  <<: *defaults
